config/routes.rb
Rails.application.routes.draw do
  get 'welcome/index'

  resources :proyectos do
    resources :requerimientos do
      resources :tareas do
        resources :registro_horas
      end
    end
  end
  resources :registro_horas
  resources :recursos

  root 'welcome#index'

  get "recursos/new" => "recursos#new"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/proyecto.rb
class Proyecto < ApplicationRecord
  has_many :requerimientos, dependent: :destroy
  validates :nombre, presence: true, length: { minimum: 5 }
  validates :descripcion, presence: true, length: { minimum: 10 }
end

app/models/recurso.rb
class Recurso < ApplicationRecord
  validates :nombre, presence: true, length: { minimum: 5 }
end

app/models/registro_hora.rb
class RegistroHora < ApplicationRecord
  belongs_to :tarea
  validates :horas, numericality: {
    greater_than: 0,
    message: "cargadas deben ser mayores a cero." }
end

app/models/requerimiento.rb
class Requerimiento < ApplicationRecord
  belongs_to :proyecto
  has_many :tareas, dependent: :destroy
  validates :nombre, presence: true, length: { minimum: 5 }
  validates :descripcion, presence: true, length: { minimum: 10 }
end

app/models/tarea.rb
class Tarea < ApplicationRecord
  belongs_to :requerimiento
  has_many :registro_horas, dependent: :destroy
  validates :descripcion, presence: true, length: {
    minimum: 5
  }
  validates :horas_estimadas, presence: true, numericality: {
    greater_than: 0,
    message: "deben ser mayores a cero."
  }
  validates :horas_cargadas, numericality: {
    less_than_or_equal_to: :horas_estimadas,
    message: "no deben superar a las horas estimadas."
  }
  before_save :default_values

  def default_values
    self.estado = 'Inicial' if self.estado.nil?
    self.horas_cargadas = 0 if self.horas_cargadas.nil?
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/proyectos_controller.rb
class ProyectosController < ApplicationController
  def index
    @proyectos = Proyecto.all
  end

  def show
    @proyecto = Proyecto.find(params[:id])
  end

  def new
    @proyecto = Proyecto.new
  end

  def edit
    @proyecto = Proyecto.find(params[:id])
  end

  def create
    @proyecto = Proyecto.new(proyecto_params)

    if @proyecto.save
      flash[:notice] = "El proyecto fue creado satisfactoriamente."
      redirect_to @proyecto
    else
      render 'new'
    end
  end

  def update
    @proyecto = Proyecto.find(params[:id])

    if @proyecto.update(proyecto_params)
      redirect_to @proyecto
    else
      render 'edit'
    end
  end

  def destroy
    @proyecto = Proyecto.find(params[:id])
    @proyecto.destroy

    redirect_to proyectos_path
  end

  private
    def proyecto_params
      params.require(:proyecto).permit(:nombre, :descripcion)
    end
end

app/controllers/recursos_controller.rb
class RecursosController < ApplicationController
    def index
        @recursos = Recurso.all
    end
    
    def show
        @recurso = Recurso.find(params[:id])
    end
    
    def new
        @recurso = Recurso.new
    end

    def create
        @recurso = Recurso.new(recurso_params)
     
        if @recurso.save
          redirect_to @recurso
        else
          render 'new'
        end
    end

    def update
        @recurso = Recurso.find(params[:id])
    
        if @recurso.update(recurso_params)
          redirect_to @recurso
        else
          render 'edit'
        end
      end
    
    def destroy
        @recurso = Recurso.find(params[:id])
        @recurso.destroy
    
        redirect_to recursos_path
      end

    private
        def recurso_params
        params.require(:recurso).permit(:nombre, :rol)
        end
end

app/controllers/registro_horas_controller.rb
class RegistroHorasController < ApplicationController
  def index
    @proyectos = Proyecto.all
  end

  def create
    @proyecto = Proyecto.find(params[:proyecto_id])
    @requerimiento = @proyecto.requerimientos.find(params[:requerimiento_id])
    @tarea = @requerimiento.tareas.find(params[:tarea_id])
    horas_cargadas_prev = @tarea.horas_cargadas + 0
    horas_cargadas_post = @tarea.horas_cargadas + params['registro_hora']['horas'].to_i
    suma = 0
    @tarea.registro_horas.each do |registro_hora|
      suma += registro_hora.horas if registro_hora.fecha == params['registro_hora']['fecha'].to_date
    end
    puts suma
    if (suma + params['registro_hora']['horas'].to_i) > 8
      @tarea.errors.add(:horas_cargadas, ': no pueden ser más de ocho por día.')
      render 'tareas/show'
    else
      @registro_hora = @tarea.registro_horas.create(registro_horas_params)
      if !@registro_hora.errors.any?
        if @tarea.update({"horas_cargadas" => horas_cargadas_post})
          if ((@tarea.horas_cargadas == @tarea.horas_estimadas) && !@tarea.errors.any? )
            @tarea.update({"estado" => "Finalizado"})
            flash[:notice] = "¡Enhorabuena! ¡Has finalizado la tarea!."
          end
          redirect_to [@tarea.requerimiento.proyecto, @tarea.requerimiento, @tarea]
        else
          @tarea.registro_horas.delete(@registro_hora.id)
          @registro_hora.destroy
          @tarea.horas_cargadas = horas_cargadas_prev
          render 'tareas/show'
        end
      else
        render 'tareas/show'
      end
    end
  end

  private
    def registro_horas_params
      params.require(:registro_hora).permit(:horas, :recurso, :fecha)
    end
end

app/controllers/requerimientos_controller.rb
class RequerimientosController < ApplicationController
  def index
    @requerimiento = Requerimiento.all
  end

  def show
    @proyecto = Proyecto.find(params[:proyecto_id])
    @requerimiento = Requerimiento.find(params[:id])
  end

  def edit
    @proyecto = Proyecto.find(params[:proyecto_id])
    @requerimiento = Requerimiento.find(params[:id])
    #@requerimiento = @proyecto.requerimientos.find(params[:id])
  end

  def create
    @proyecto = Proyecto.find(params[:proyecto_id])
    @requerimiento = @proyecto.requerimientos.create(requerimiento_params)
    flash[:notice] = "El requerimiento #{@requerimiento.id} fue creado satisfactoriamente."
    redirect_to proyecto_path(@proyecto)
  end

  def destroy
    @proyecto = Proyecto.find(params[:proyecto_id])
    @requerimiento = @proyecto.requerimientos.find(params[:id])
    @requerimiento.destroy
    redirect_to proyecto_path(@proyecto)
  end

  def update
    @requerimiento = Requerimiento.find(params[:id])
    @proyecto = Proyecto.find(params[:proyecto_id])

    if @requerimiento.update(requerimiento_params)
      redirect_to proyecto_path(@proyecto)
    else
      render 'edit'
    end
  end

  private
    def requerimiento_params
      params.require(:requerimiento).permit(:nombre, :descripcion)
    end
end

app/controllers/tareas_controller.rb
class TareasController < ApplicationController
  def index
    @tarea = Tarea.all
  end

  def show
    @tarea = Tarea.find(params[:id])
    @proyecto = Proyecto.find(params[:proyecto_id])
    @requerimiento = @proyecto.requerimientos.find(params[:requerimiento_id])
  end

  def edit
    @tarea = Tarea.find(params[:id])
    @proyecto = Proyecto.find(params[:proyecto_id])
    @requerimiento = @proyecto.requerimientos.find(params[:requerimiento_id])
  end

  def create
    @proyecto = Proyecto.find(params[:proyecto_id])
    @requerimiento = @proyecto.requerimientos.find(params[:requerimiento_id])
    params['tarea']['horas_cargadas'] = 0
    puts tareas_params
    @tarea = @requerimiento.tareas.create(tareas_params)
    if !@tarea.errors.any?
      flash[:notice] = "La tarea #{@tarea.id} fue creada satisfactoriamente."
      redirect_to proyecto_requerimiento_path(:id => @requerimiento.id)
    else
      render 'requerimientos/show'
    end
  end

  def destroy
    @proyecto = Proyecto.find(params[:proyecto_id])
    @requerimiento = @proyecto.requerimientos.find(params[:requerimiento_id])
    @tarea = @requerimiento.tareas.find(params[:id])
    @tarea.destroy
    redirect_to proyecto_requerimiento_path(:id => @requerimiento.id)
  end

  def update
    @tarea = Tarea.find(params[:id])
    @requerimiento = Requerimiento.find(params[:requerimiento_id])
    @proyecto = Proyecto.find(params[:proyecto_id])

    if @tarea.update(tareas_params)
      redirect_to proyecto_requerimiento_tarea_path(@tarea)
    else
      render 'edit'
    end
  end

  private
    def tareas_params
      params.require(:tarea).permit(:descripcion, :horas_estimadas,
        :horas_cargadas, :fecha, :empleado, :estado)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>TimeTracker</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= stylesheet_link_tag "styles.css" %>
  </head>

  <body>
    <nav class="navbar navbar-expand-md navbar-dark fixed-top bg-dark">
      <a class="navbar-brand" href="/">Time Tracker</a>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarCollapse" aria-controls="navbarCollapse" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>
      <div class="collapse navbar-collapse" id="navbarCollapse">
        <ul class="navbar-nav mr-auto">
          <li class="nav-item active">
            <a class="nav-link" href="/">Home <span class="sr-only">(current)</span></a>
          </li>
          <li class="nav-item">
            <%= link_to 'Proyectos', proyectos_path, :class => "nav-link" %>
          </li>
          <li class="nav-item">
            <a class="nav-link" href="#">Clientes</a>
          </li>
          <li class="nav-item">
            <%= link_to 'Recursos', recursos_path, :class => "nav-link" %>
          </li>
          <li class="nav-item">
            <%= link_to 'Mis tareas', registro_horas_path, :class => "nav-link" %>
          </li>
        </ul>
        <form class="form-inline mt-2 mt-md-0">
          <input class="form-control mr-sm-2" type="text" placeholder="Buscar" aria-label="Buscar">
          <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Buscar</button>
        </form>
      </div>
    </nav>

    <main role="main" class="container">
        <%= yield %>
    </main>
  </body>
</html>

app/views/proyectos/edit.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="/">Home</a></li>
    <li class="breadcrumb-item"><%= link_to 'Proyectos', proyectos_path %></li>
    <li class="breadcrumb-item active" aria-current="page"><%= @proyecto.nombre %></li>
  </ol>
</nav>

<h2>Editar proyecto</h2>

<%= form_with model: @proyecto, local: true do |form| %>

  <% if @proyecto.errors.any? %>
    <div id="error_explanation">
      <h2>
        <%= pluralize(@proyecto.errors.count, "error") %> prohibited
        this project from being saved:
      </h2>
      <ul>
        <% @proyecto.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :nombre %><br>
    <%= form.text_field :nombre, :class => "form-control"  %>
  </div>

  <div class="form-group">
    <%= form.label :descripcion %><br>
    <%= form.text_area :descripcion, :class => "form-control" %>
  </div>

  <p>
    <%= form.submit "Actualizar proyecto" %>
  </p>

<% end %>

<%= link_to 'Atrás', proyectos_path,
    :class => "btn btn-secondary btn-sm" %>

app/views/proyectos/index.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="/">Home</a></li>
    <li class="breadcrumb-item active" aria-current="page">Proyectos</li>
  </ol>
</nav>

<h1>Proyectos</h1>
<hr>
<%= link_to 'Nuevo proyecto', new_proyecto_path,
    :id => "nuevo_proyecto", :class => "btn btn-secondary" %>
<p>
  <table class="table table-hover">
    <thead class="thead-dark">
      <tr>
        <th scope="col">ID</th>
        <th scope="col">Nombre</th>
        <th scope="col">Descripción</th>
        <th scope="col">Opciones</th>
      </tr>
    </thead>
    <tbody>
    <% @proyectos.each do |proyecto| %>
      <tr>
        <th scoe="row"><%= proyecto.id %></td>
        <td><%= proyecto.nombre %></td>
        <td><%= proyecto.descripcion %></td>
        <td class="btn-group text-right" role="group" aria-label="opciones" data-align="right">
          <%= link_to 'Mostrar', proyecto_path(proyecto),
              :class => "btn btn-secondary btn-sm" %>
          <%= link_to 'Editar', edit_proyecto_path(proyecto),
              :class => "btn btn-secondary btn-sm" %>
          <%= link_to 'Eliminar', proyecto_path(proyecto),
              :class => "btn btn-secondary btn-sm",
              method: :delete,
              data: { confirm: '¿Estás seguro?' } %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
</p>

app/views/proyectos/new.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="/">Home</a></li>
    <li class="breadcrumb-item"><%= link_to 'Proyectos', proyectos_path %></li>
    <li class="breadcrumb-item active" aria-current="page">Nuevo proyecto</li>
  </ol>
</nav>

<h2>Nuevo proyecto</h2><hr>

<%= form_with model: @proyecto, local: true do |form| %>

  <% if @proyecto.errors.any? %>
    <div id="error_explanation" class="alert alert-danger" role="alert">
      <h3>
        <%= pluralize(@proyecto.errors.count, "error") %> prohibited
        this project from being saved:
      </h3>
      <ul>
        <% @proyecto.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="form-group">
    <%= form.label :nombre %><br>
    <%= form.text_field :nombre, :class => "form-control"  %>
  </div>

  <div class="form-group">
    <%= form.label :descripcion %><br>
    <%= form.text_area :descripcion, :class => "form-control" %>
  </div>

  <p>
    <%= form.submit "Crear proyecto", :id => "crear_proyecto" %>
  </p>

<% end %>

<%= link_to 'Atrás', proyectos_path,
    :class => "btn btn-secondary btn-sm" %>

app/views/proyectos/show.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="/">Home</a></li>
    <li class="breadcrumb-item"><%= link_to 'Proyectos', proyectos_path %></li>
    <li class="breadcrumb-item active" aria-current="page"><%= @proyecto.nombre %></li>
  </ol>
</nav>

<% if flash[:notice] %>
  <div class="alert alert-success" role="alert"><%= flash[:notice] %></div>
<% end %>

<h2>Detalles del proyecto</h2><hr>
<p>
  <strong>Nombre:</strong>
  <%= @proyecto.nombre %>
</p>

<p>
  <strong>Descripción:</strong>
  <%= @proyecto.descripcion %>
</p>

<hr>

<h3>Requerimientos</h3>

<p>
  <button class="btn btn-secondary" type="button" data-toggle="collapse" data-target="#nuevoRequerimiento"
          aria-expanded="false" aria-controls="nuevoRequerimiento" id="nuevo_requerimiento">
    Nuevo requerimiento
  </button>
</p>

<div class="collapse" id="nuevoRequerimiento">
  <div class="card card-body">
    <h3>Agregar requerimiento</h3>
    <%= render 'requerimientos/form' %>
  </div>
</div>

<p>
  <table class="table table-hover">
    <thead class="thead-dark">
      <tr>
        <th scope="col">ID</th>
        <th scope="col">Nombre</th>
        <th scope="col">Descripción</th>
        <th scope="col">Opciones</th>
      </tr>
    </thead>
    <tbody>
    <% @proyecto.requerimientos.each do |requerimiento| next if requerimiento.new_record? %>
      <tr>
        <th scoe="row"><%= requerimiento.id %></td>
        <td><%= requerimiento.nombre %></td>
        <td><%= requerimiento.descripcion %></td>
        <td class="btn-group text-right" role="group" aria-label="opciones" data-align="right">
          <%= link_to 'Mostrar', [requerimiento.proyecto, requerimiento],
              :class => "btn btn-secondary btn-sm" %>
          <%= link_to 'Editar', edit_proyecto_requerimiento_path(@proyecto, requerimiento),
              :class => "btn btn-secondary btn-sm" %>
          <%= link_to 'Eliminar', [requerimiento.proyecto, requerimiento],
              :class => "btn btn-secondary btn-sm",
              method: :delete,
              data: { confirm: '¿Estás seguro?' } %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
</p>
<hr>

<%= link_to 'Editar proyecto', edit_proyecto_path(@proyecto),
    :class => "btn btn-secondary btn-sm" %>
<%= link_to 'Atrás', proyectos_path,
    :class => "btn btn-secondary btn-sm" %>

app/views/recursos/_form.html.erb
<%= form_with model: @recurso, local: true do |form| %>

    <% if @recurso.errors.any? %>
      <div id="error_explanation">
        <h2>
          <%= pluralize(@recurso.errors.count, "error") %> prohibited
          this project from being saved:
        </h2>
        <ul>
          <% @recurso.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
  
    <div class="form-group">
      <%= form.label :nombre %><br>
      <%= form.text_field :nombre, :class => "form-control"  %>
    </div>
  
    <div class="form-group">
      <%= form.label :rol %><br>
      <%= form.text_area :rol, :class => "form-control" %>
    </div>
  
    <p>
      <%= form.submit %>
    </p>
  
  <% end %>
  

app/views/recursos/index.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="/">Home</a></li>
    <li class="breadcrumb-item active" aria-current="page">Recursos</li>
  </ol>
</nav>


<h1>Recursos</h1>
<hr>
<%= link_to 'Nuevo Recurso', new_recurso_path,
:class => "btn btn-secondary" %>

<p>
  <table class="table table-hover">
    <thead class="thead-dark">
      <tr>
        <th scope="col">ID</th>
        <th scope="col">Nombre</th>
        <th scope="col">Rol</th>
        <th scope="col">Opciones</th>
      </tr>
    </thead>
    <% @recursos.each do |recurso| %>
      <tr>
        <th scoe="row"><%= recurso.id %></td>
        <td><%= recurso.nombre %></td>
        <td><%= recurso.rol %></td>
        <td class="btn-group text-right" role="group" aria-label="opciones" data-align="right">
          <%= link_to 'Mostrar', recurso_path(recurso),
              :class => "btn btn-secondary btn-sm" %>
          <%= link_to 'Editar', edit_recurso_path(recurso),
              :class => "btn btn-secondary btn-sm" %>
          <%= link_to 'Eliminar', recurso_path(recurso),
              :class => "btn btn-secondary btn-sm",
              method: :delete,
              data: { confirm: '¿Estás seguro?' } %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
</p>

app/views/recursos/new.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="/">Home</a></li>
    <li class="breadcrumb-item"><%= link_to 'Recursos', recursos_path %></li>
    <li class="breadcrumb-item active" aria-current="page">Nuevo Recurso</li>
  </ol>
</nav>


<h2>Nuevo Recurso</h2>

<%= render 'form' %>

<%= link_to 'Atrás', recursos_path,
    :class => "btn btn-secondary btn-sm" %>

app/views/recursos/show.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="/">Home</a></li>
    <li class="breadcrumb-item"><%= link_to 'Recursos', recursos_path %></li>
    <li class="breadcrumb-item active" aria-current="page"><%= @recurso.nombre %></li>
  </ol>
</nav>

<h2>Detalle</h2><hr>
<p>
  <strong>Nombre:</strong>
  <%= @recurso.nombre %>
</p>
 
<p>
  <strong>Rol:</strong>
  <%= @recurso.rol %>
</p>

<%= link_to 'Atrás', recursos_path,
    :class => "btn btn-secondary btn-sm" %>

app/views/requerimientos/_form.html.erb
<%= form_with(model: [ @proyecto, @proyecto.requerimientos.build ], local: true) do |form| %>
  <div class="form-group">
    <%= form.label :nombre %><br>
    <%= form.text_field :nombre, :class => "form-control"  %>
  </div>
  <div class="form-group">
    <%= form.label :descripcion %><br>
    <%= form.text_area :descripcion, :class => "form-control"  %>
  </div>
  <div class="form-group">
    <%= form.submit "Crear requerimiento", :id => "crear_requerimiento" %>
  </div>
<% end %>

app/views/requerimientos/show.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="/">Home</a></li>
    <li class="breadcrumb-item"><%= link_to 'Proyectos', proyectos_path %></li>
    <li class="breadcrumb-item"><%= link_to @proyecto.nombre, proyecto_path(@proyecto) %></li>
    <li class="breadcrumb-item active" aria-current="page"><%= @requerimiento.nombre %></li>
  </ol>
</nav>

<% if flash[:notice] %>
  <div class="alert alert-success" role="alert"><%= flash[:notice] %></div>
<% end %>

<% if (!@tarea.nil? && @tarea.errors.any?) %>
  <div id="error_explanation" class="alert alert-danger" role="alert">
    <ul>
      <% @tarea.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
<% end %>

<h2>Detalles del requerimiento</h2>
<hr>
<p>
  <strong>Nombre:</strong>
  <%= @requerimiento.nombre %>
</p>

<p>
  <strong>Descripción:</strong>
  <%= @requerimiento.descripcion %>
</p>

<hr>

<h3>Tareas</h3>

<p>
  <button class="btn btn-secondary" type="button" data-toggle="collapse" data-target="#nuevaTarea"
          aria-expanded="false" aria-controls="nuevaTarea" id="nueva_tarea">
    Nueva tarea
  </button>
</p>

<div class="collapse" id="nuevaTarea">
  <div class="card card-body">
    <h3>Agregar tarea</h3>
    <%= render 'tareas/form' %>
  </div>
</div>

<p>
  <table class="table table-hover">
    <thead class="thead-dark">
      <tr>
        <th scope="col">ID</th>
        <th scope="col">Descripción</th>
        <th scope="col">Estado</th>
        <th scope="col">Empleado</th>
        <th scope="col">Horas estimadas</th>
        <th scope="col">Horas cargadas</th>
        <th scope="col">Opciones</th>
      </tr>
    </thead>
    <tbody>
    <% @requerimiento.tareas.each do |tarea| next if tarea.new_record? %>
      <tr>
        <th scoe="row"><%= tarea.id %></td>
        <td><%= tarea.descripcion %></td>
        <td><%= tarea.estado %></td>
        <td><%= tarea.empleado %></td>
        <td><%= tarea.horas_estimadas %></td>
        <td><%= tarea.horas_cargadas %></td>
        <td class="btn-group text-right" role="group" aria-label="opciones" data-align="right">
          <%= link_to 'Mostrar', [tarea.requerimiento.proyecto, tarea.requerimiento, tarea],
              :class => "btn btn-secondary btn-sm" %>
          <%= link_to 'Editar', edit_proyecto_requerimiento_tarea_path(tarea.requerimiento.proyecto, tarea.requerimiento, tarea),
              :class => "btn btn-secondary btn-sm" %>
          <%= link_to 'Eliminar', [tarea.requerimiento.proyecto, tarea.requerimiento, tarea],
              :class => "btn btn-secondary btn-sm",
              method: :delete,
              data: { confirm: '¿Estás seguro?' } %>
        </td>
      </tr>
    <% end %>
    </tbody>
  </table>
</p>

<hr>
<%= link_to 'Editar requerimiento', '#',
    :class => "btn btn-secondary btn-sm" %>
<%= link_to 'Atrás', proyecto_path(@proyecto),
    :class => "btn btn-secondary btn-sm" %>

app/views/tareas/edit.html.erb
<nav aria-label="breadcrumb">
  <ol class="breadcrumb">
    <li class="breadcrumb-item"><a href="/">Home</a></li>
    <li class="breadcrumb-item"><%= link_to 'Proyectos', proyectos_path %></li>
    <li class="breadcrumb-item"><%= link_to @proyecto.nombre, proyecto_path(@proyecto) %></li>
    <li class="breadcrumb-item"><%= link_to @requerimiento.nombre, proyecto_requerimiento_path(:id => @requerimiento.id) %></li>
    <li class="breadcrumb-item active" aria-current="page"><%= @tarea.descripcion %></li>
  </ol>
</nav>

<h2>Cargar horas en tarea <% @tarea.descripcion %></h2>
<hr>
<%= form_for ([@proyecto, @requerimiento, @tarea]), :class => "form-inline" do |form| %>
  <fieldset disabled>
  <div class="form-group">
    <%= form.label :descripcion %><br>
    <%= form.text_field :descripcion, :class => "form-control"  %>
  </div>
  <div class="form-group">
    <%= form.label :empleado %><br>
    <%= form.text_field :empleado, :class => "form-control"  %>
  </div>
  <div class="form-group form-row">
    <div class="col-6">
    <%= form.label :horas_estimadas %><br>
    <%= form.number_field :horas_estimadas, :class => "form-control"  %>
    </div>
    <div class="col-6">
    <%= form.label :horas_cargadas %><br>
    <%= form.number_field :horas_cargadas, :class => "form-control"  %>
    </div>
  </div>
  </fieldset>
  <div class="form-group form-row">
    <div class="col-6">
    <%= form.label :horas_cargadas %><br>
    <%= form.number_field :horas_cargadas, :class => "form-control"  %>
    </div>
    <div class="col-6">
    <%= form.label :fecha %><br>
    <%= form.date_field :fecha, :class => "form-control"  %>
    </div>
  </div>
  <p>
    <%= form.submit %>
  </p>
<% end %>

<%= link_to 'Atrás', registro_horas_path,
    :class => "btn btn-secondary btn-sm" %>